export enum CoreCatalogueTypeEnum {
  inspections_state = 'inspections_state',
  processes_state = 'processes_state',
  cadastres_state = 'cadastres_state',
  dpa_zone = 'dpa_zone',
  activities_geographic_area = 'activities_geographic_area',
  internal_zonal_users_zone = 'internal_zonal_users_zone',
  processes_legal_entity = 'processes_legal_entity',
  ctc_activities = 'ctc_activities',
  tourist_transport_companies_type = 'tourist_transport_companies_type',
  cadastre_states_state = 'cadastre_states_state',
  establishments_state = 'establishments_state',
  adventure_tourism_modalities = 'adventure_tourism_modalities',
  adventure_tourism_modalities_air = 'adventure_tourism_modalities_air',
  adventure_tourism_modalities_land = 'adventure_tourism_modalities_land',
  adventure_tourism_modalities_water = 'adventure_tourism_modalities_water',
  process_agency_permanent_physical_space = 'process_agency_permanent_physical_space',
  processes_local_type = 'processes_local_type',
  internal_inactivation_causes = 'internal_inactivation_causes',
  inactivation_cause_type = 'inactivation_cause_type',
  complementary_services_model = 'complementary_services_model',
  rooms_room_type = 'rooms_room_type',
  breach_causes = 'breach_causes',
  complementary_services_entity = 'complementary_services_entity',
  activities_types_kitchens_continent = 'activities_types_kitchens_continent',
  activities_type_establishments = 'activities_type_establishments',
  activities_types_services_continent = 'activities_types_services_continent',
  kitchen_types_continent = 'kitchen_types_continent',
  ruc_types = 'ruc_types',
  process_food_drinks_establishment_type = 'process_food_drinks_establishment_type',
  service_types_continent = 'service_types_continent',
  transporte_tipo_vehiculos = 'transporte_tipo_vehiculos',
  process_transport_airline_type = 'process_transport_airline_type',
  requirement_item = 'requirement_item',
}

export enum CatalogueInspectionsStateEnum {
  autogenerated_1 = 'autogenerated_1',
  autogenerated_2 = 'autogenerated_2',
  requested = 'requested',
  scheduled = 'scheduled',
  confirmed = 'confirmed',
  rescheduled_1 = 'rescheduled_1',
  rescheduled_2 = 'rescheduled_2',
}

export enum CatalogueProcessesTypeEnum {
  registration = 'registration',
  update = 'update',
  inactivation = 'inactivation',
  new_classification = 'new_classification',
  new_activity = 'new_activity',
  readmission = 'readmission',
  reclassification = 'reclassification',
  recategorization = 'recategorization',
}

export enum CatalogueProcessesStateEnum {
  pending_1 = 'pending_1',
  pending_2 = 'pending_2',
  completed = 'completed',
}

export enum CatalogueActivitiesCodeEnum {
  accommodation_continent = 'accommodation_continent',
  accommodation_galapagos = 'accommodation_galapagos',
  agency_continent = 'agency_continent',
  agency_galapagos = 'agency_galapagos',
  ctc_continent = 'ctc_continent',
  ctc_galapagos = 'ctc_galapagos',
  event_continent = 'events_continent',
  event_galapagos = 'events_galapagos',
  food_drink_continent = 'food_drink_continent',
  food_drink_galapagos = 'food_drink_galapagos',
  park_continent = 'park_continent',
  park_galapagos = 'park_galapagos',
  transport_continent = 'transport_continent',
  transport_galapagos = 'transport_galapagos',
}

export enum CatalogueCadastresStateEnum {
  pending = 'pending',
  ratified = 'ratified',
  inactive = 'inactive',
  temporary_suspension = 'temporary_suspension',
  definitive_suspension = 'definitive_suspension',
  recategorized = 'recategorized',
  reclassified = 'reclassified',
}

export enum CatalogueSchoolPeriodStateEnum {
  OPEN = 'open',
  CLOSE = 'close',
}

export enum CatalogueSchoolPeriodTypeEnum {
  ORDINARY = 'ordinary',
  EXTRAORDINARY = 'extraordinary',
  ESPECIAL = 'especial',
}

export enum CatalogueSubjectRequirementTypeEnum {
  PREREQUISITE = 'prerequisite',
  CO_REQUISITE = 'co_requisite',
}

export enum CatalogueCareersModalityEnum {
  ON_SITE = 'on-site',
  SEMI_ON_SITE = 'semi-on-site',
  DISTANCE = 'distance',
  DUAL = 'dual',
  ONLINE = 'online',
  HYBRID = 'hybrid',
}

export enum CatalogueYesNoEnum {
  YES = '1',
  NO = '2',
}

export enum UsersIdentificationTypeStateEnum {
  IDENTIFICATION = '1',
  PASSPORT = '2',
}

export enum CatalogueMaritalStatusEnum {
  SINGLE = 'single',
  MARRIED = 'married',
  WIDOWER = 'widower',
  DIVORCED = 'divorced',
  FREE_UNION = 'free_union',
}

export enum CatalogueEthnicOriginEnum {
  INDIGENOUS = 'indigenous',
  AFRO_ECUADORIAN = 'afro_ecuadorian',
  MONTUBIO = 'montubio',
  HALF_BLOOD = 'half_blood',
  WHITE = 'white',
}

export enum CatalogueTypeSchoolEnum {
  FISCAL = 'fiscal',
  FISCOMISIONAL = 'fiscomisional',
  PARTICULAR = 'particular',
  MUNICIPAL = 'municipal',
}

export enum CatalogueStudentLiveEnum {
  ALONE = 'alone',
  BOTH_PARENTS = 'both_parents',
  MOTHER = 'mother',
  FATHER = 'father',
  SPOUSE = 'spouse',
  GRANDPARENTS = 'grandparents',
  OTHER = 'other',
}

export enum CatalogueEconomicContributionEnum {
  PARENTS = 'parents',
  GRAND_PARENTS = 'grand_parents',
  FAMILY = 'family',
  OWN_SALARY = 'own_salary',
  OTHER = 'other',
}

export enum CatalogueEstablishmentsStateEnum {
  open = 'abierto',
  closed = 'cerrado',
}

export enum CatalogueProcessGuidesCodeEnum {
  pane = 'pane',
  modality_adventure = 'modality_aventure',
  certification_language = 'certification_language',
  modality_adventure_guide = 'modality_aventure_guide',
  high_mountain = 'alm',
  mid_mountain = 'mem',
  vehicle_registration = 'vehicle_registration',
  document_vehicle_inspection = 'document_vehicle_inspection',
  accident_policy = 'accident_policy',
}

export enum CatalogueProfessionalTitlesLevelEnum {
  bachiller = 'bachiller',
  tercer_nivel = 'tercer_nivel',
  cuarto_nivel = 'cuarto_nivel',
  phd = 'phd',
}
