export enum AuthRepositoryEnum {
  AUDIT_REPOSITORY = 'AUDIT_REPOSITORY',
  MENU_REPOSITORY = 'MENU_REPOSITORY',
  PERMISSION_REPOSITORY = 'PERMISSION_REPOSITORY',
  ROLE_REPOSITORY = 'ROLE_REPOSITORY',
  TRANSACTIONAL_CODE_REPOSITORY = 'TRANSACTIONAL_CODE_REPOSITORY',
  SECURITY_QUESTION_REPOSITORY = 'SECURITY_QUESTION_REPOSITORY',
  EMAIL_VERIFICATION_REPOSITORY = 'EMAIL_VERIFICATION_REPOSITORY',
  USER_REPOSITORY = 'USER_REPOSITORY',
}

export enum CommonRepositoryEnum {
  FILE_REPOSITORY = 'FILE_REPOSITORY',
  CATALOGUE_REPOSITORY = 'CATALOGUE_REPOSITORY',
  DPA_REPOSITORY = 'DPA_REPOSITORY',
  PROVINCE_REPOSITORY = 'PROVINCE_REPOSITORY',
}

export enum CoreRepositoryEnum {
  BRANCH_REPOSITORY = 'BRANCH_REPOSITORY',
  CUSTOMER_REPOSITORY = 'CUSTOMER_REPOSITORY',
  STAFF_PROFILE_REPOSITORY = 'STAFF_PROFILE_REPOSITORY',
  STAFF_WORKING_HOUR_REPOSITORY = 'STAFF_WORKING_HOUR_REPOSITORY',
  STAFF_TIME_OFF_REPOSITORY = 'STAFF_TIME_OFF_REPOSITORY',
  SERVICE_REPOSITORY = 'SERVICE_REPOSITORY',
  APPOINTMENT_REPOSITORY = 'APPOINTMENT_REPOSITORY',
  APPOINTMENT_SERVICE_REPOSITORY = 'APPOINTMENT_SERVICE_REPOSITORY',
  PRODUCT_REPOSITORY = 'PRODUCT_REPOSITORY',
  STOCK_BALANCE_REPOSITORY = 'STOCK_BALANCE_REPOSITORY',
  SUPPLIER_REPOSITORY = 'SUPPLIER_REPOSITORY',
  PURCHASE_REPOSITORY = 'PURCHASE_REPOSITORY',
  PURCHASE_ITEM_REPOSITORY = 'PURCHASE_ITEM_REPOSITORY',
  INVENTORY_MOVEMENT_REPOSITORY = 'INVENTORY_MOVEMENT_REPOSITORY',
  INVOICE_REPOSITORY = 'INVOICE_REPOSITORY',
  INVOICE_ITEM_REPOSITORY = 'INVOICE_ITEM_REPOSITORY',
  PAYMENT_REPOSITORY = 'PAYMENT_REPOSITORY',
}
